---
title: "03_Tidy_data"
author: "Yiman Rui"
date: "2026-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Tidy Data"
output: github_document
---

This file is for doing data tidying. 

```{r}
library(tidyverse)
```

## Let's tidy some data!

```{r}
pulse_df = 
  haven::read_sas("~/Desktop/Data Science/Data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()
```


Okay, let's tidy!

```{r, eval = FALSE}
pulse_tidy_df =
  pulse_df |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi_score"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
```

Just use once ..

```{r}
pulse_df = 
  haven::read_sas("~/Desktop/Data Science/Data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi_score"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
```


Let's practice!

Import the litters data; keep columns litter number and GD weights; and tidy.

```{r}
litters_df = 
  read_csv("~/Desktop/Data Science/Data/FAS_litters.csv", na = c(".", "", "NA")) |> 
  janitor::clean_names() |> 
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight"
  ) |> 
  mutate(
    gd = case_match(
      gd, 
      "gd0_weight"  ~ 0, 
      "gd18_weight" ~ 18, 
    )
  )
```


```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
```
```{r}
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")

```
## bind some rows

```{r}
fellowship_df = 
  readxl::read_excel("~/Desktop/Data Science/Data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship")

two_towers_df = 
  readxl::read_excel("~/Desktop/Data Science/Data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two towers")

return_df = 
  readxl::read_excel("~/Desktop/Data Science/Data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return of the king")
```

Pull all together and tidy

```{r}
lotr_tidy = 
  bind_rows(fellowship_df, two_towers_df, return_df) |>
  janitor::clean_names() |>
  relocate(movie) |>
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```

